export let IDENTIFY_CANDIDATE = "IDENTIFY_CANDIDATE";
export let LOGOUT_CANDIDATE = "LOGOUT_CANDIDATE";
export let LOGIN_CANDIDATE = "LOGIN_CANDIDATE";
export let CANDIDATE_AUTH_IN_PROGRESS = "CANDIDATE_AUTH_IN_PROGRESS";
export let CANDIDATE_SKILLS_UPDATE = "CANDIDATE_SKILLS_UPDATE";
export let UPDATE_LOGGED_CANDIDATE = "UPDATE_LOGGED_CANDIDATE";
export let IDENTIFY_EMPLOYER = "IDENTIFY_EMPLOYER";
export let LOGOUT_EMPLOYER = "LOGOUT_EMPLOYER";
export let LOGIN_EMPLOYER = "LOGIN_EMPLOYER";
export let EMPLOYER_AUTH_IN_PROGRESS = "EMPLOYER_AUTH_IN_PROGRESS";
export let UPDATE_LOGGED_EMPLOYER = "UPDATE_LOGGED_EMPLOYER";

